INSERT INTO STUDENT (STUDENT_NAME, COURSE_NAME, CAMPUS_NAME) VALUES ('Ali Kachef', 'Spring Boot', 'GenSpark');
INSERT INTO STUDENT (STUDENT_NAME, COURSE_NAME, CAMPUS_NAME) VALUES ('Hassan', 'Java Core', 'It tech');
INSERT INTO STUDENT (STUDENT_NAME, COURSE_NAME, CAMPUS_NAME) VALUES ('Islam', 'QA Tester', 'Test pro');
INSERT INTO STUDENT (STUDENT_NAME, COURSE_NAME, CAMPUS_NAME) VALUES ('Mohammad', 'Analysis', 'Test Pro');
